title: Jay Verma Trivedi
description: Astrophysics | Gravitation | Singularities | Cosmic Censorship
theme: minima

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed
header_pages:
  - research.md
  - blog.md
  - cv.md
  - search.md
  - contact.md
